#! /bin/sh

##cool ass autostart

pgrep -x sxhkd > /dev/null || sxhkd &

picom &

feh --randomize --bg-fill /home/rat/Downloads/walls/* &

$HOME/.config/polybar/launch.sh &

emacs &

firefox &

spotify &

##cool ass autostart


bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a firefox desktop='^9'

bspc rule -a Spotify desktop='^2'

bspc rule -a Emacs desktop='^1'

bspc rule -a Emacs state=tiled &




bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0
bspc config bottom_padding       0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#F81894"
bspc config normal_border_color      "#202A25"







